// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Props every page receives; see `frontend/src/inertia.d.ts`.
 */
export type AppShared = { app_name: string, 
/**
 * When the shared data was first loaded: a once prop, so it stays the same while the
 * visitor navigates (the server skips it once the client has it).
 */
loaded_at?: string, };
