// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The contact form, also the type of the frontend `useForm` data.
 */
export type ContactForm = { name: string, email: string, message: string, };
