// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Post } from "./Post";
import type { ScrollData } from "./ScrollData";
import type { Stats } from "./Stats";

/**
 * `posts` is an infinite scroll prop (`<InfiniteScroll data="posts">`). `stats` (deferred)
 * and `categories` (optional) are added as lazy props by the controller; they are declared
 * here so the frontend type has them.
 */
export type FeedProps = { posts: ScrollData<Post>, even_only: boolean, stats?: Stats, categories?: Array<string>, };
