// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire shape of a scroll prop with the default wrapper: `{ "data": [...] }`.
 */
export type ScrollData<T> = { data: Array<T>, };
